FROM node
# The minimal baseline we need for Nodejs

WORKDIR /app

# COPY the package.json file, update any deps and install them

COPY package.json .

RUN yarn install

# copy the whole source folder(the dir is relative to the Dockerfile
COPY . .

CMD [ "yarn", "run", "develop","-H","0.0.0.0"]